default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: NovaSenha123!
  host: localhost

development:
  <<: *default
  database: auth_microservice_development

test:
  <<: *default
  database: auth_microservice_test

production:
  <<: *default
  database: auth_microservice_production
  username: auth_microservice
  password: <%= ENV['AUTH_MICROSERVICE_DATABASE_PASSWORD'] %>
